[package]
name = "exercism"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "exercism"
path = "src/main.rs"

[dependencies]
itertools = "0.13.0"
libc = "0.2.169"
regex = "1.11.1"
thiserror = "2.0.11"
